// <auto-generated />
namespace Mobius.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Migration02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migration02));
        
        string IMigrationMetadata.Id
        {
            get { return "201706011753239_Migration02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
